### ISSUE TITLE
Remove console logs

### ISSUE THREAD

**Issue by Elrhino** [sheikalthaf/ngu-carousel#10]
Hi, you forgot to remove the console logs in `NguCarouselComponent.carouselScrollTwo(...)` at `console.log(this.withAnim)`. Maybe this was on purpose but it's very annoying.

Thanks!

**Comment by sheikalthaf** [comment]
Hi @Elrhino ,

Sorry for console.  I will remove this

**Comment by Elrhino** [comment]
@sheikalthaf any plan to remove this soon?

**Comment by sheikalthaf** [comment]
@Elrhino Sorry for delaying the update. i'm moving the style to flex box and other touch improvements. I will update the repo once everything goes well

**Comment by ohotniksergey** [comment]
can you please add this small update separatelly? It takes up the whole console output

**Comment by sheikalthaf** [comment]
@Elrhino @ohotniksergey  removed the console. i'm working on next update which is really big. I will push the next update in weekend
