### ISSUE TITLE
Memory leaking wile using ngu-carousel

### ISSUE THREAD

**Issue by sarnecki-cic** [sheikalthaf/ngu-carousel#103]
The problem is when I use ngu-carousel with data that is constantly changing.
After a while the app and the whole browser is stucked. It seems like the ngu-carousel stores all the data inside and it's crashing the app.

**Comment by sheikalthaf** [comment]
Duplicate of #104

**Comment by sheikalthaf** [comment]
@sarnecki-cic Thanks for reporting fixed this issue and will push the update. Thanks

**Comment by sheikalthaf** [comment]
@sarnecki-cic This isssue is fixed. Please check release.

Thanks
