### ISSUE TITLE
Add documentation about prev and next button handling

### ISSUE THREAD

**Issue by corentin-gautier** [sheikalthaf/ngu-carousel#107]
I have a carousel that display all items on desktop but only one in mobile, it used to hide the prev/next button but it doesn't anymore

**Comment by sheikalthaf** [comment]
@corentin-gautier Hi,

Now carousel won't control buttons instead it will give options to control. Please use template reference and check whether it is `isFirst`, `isLast` or `isHovered`.

Thanks

**Comment by corentin-gautier** [comment]
@sheikalthaf I can't hide if isFirst or isLast if i'm using loop: true. 

The solution I've found is to check how many pointNumbers there is (less than 2 means we can't slide) that way I still have nav buttons for looping.

**Comment by sheikalthaf** [comment]
@corentin-gautier Sorry for this but other users want to control the carousel buttons with opacity, etc..

Thats y it is removed

**Comment by corentin-gautier** [comment]
@sheikalthaf yeah sure, just add it to the readme then because other people are going to ask how to do this

**Comment by corentin-gautier** [comment]
related to #92
