### ISSUE TITLE
Some sample are not working

### ISSUE THREAD

**Issue by nhatzbulawan** [sheikalthaf/ngu-carousel#114]
import { Component } from '@angular/core';
import { NguCarousel, NguCarouselStore } from '@ngu/carousel';

@Component({
  selector: 'app-carousel',
  template: `
    <ngu-carousel
      [inputs]="carouselBanner"
      (onMove)="onmoveFn($event)">

          <ngu-item NguCarouselItem class="bannerStyle">
              <h1>1</h1>
          </ngu-item>

          <ngu-item NguCarouselItem class="bannerStyle">
              <h1>2</h1>
          </ngu-item>

          <ngu-item NguCarouselItem class="bannerStyle">
              <h1>3</h1>
          </ngu-item>

          <button NguCarouselPrev class='leftRs'>&lt;</button>
          <button NguCarouselNext class='rightRs'>&gt;</button>
    </ngu-carousel>
  `,
  styles: [
    `
    .bannerStyle h1 {
        background-color: #ccc;
        min-height: 300px;
        text-align: center;
        line-height: 300px;
    }
    .leftRs {
        position: absolute;
        margin: auto;
        top: 0;
        bottom: 0;
        width: 50px;
        height: 50px;
        box-shadow: 1px 2px 10px -1px rgba(0, 0, 0, .3);
        border-radius: 999px;
        left: 0;
    }

    .rightRs {
        position: absolute;
        margin: auto;
        top: 0;
        bottom: 0;
        width: 50px;
        height: 50px;
        box-shadow: 1px 2px 10px -1px rgba(0, 0, 0, .3);
        border-radius: 999px;
        right: 0;
    }
  `
  ]
})
export class Sample implements OnInit {
  ngOnInit() {
    this.carouselBanner = {
      grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
      slide: 1,
      speed: 400,
      interval: {
        timing: 3000,
        initialDelay: 1000
      },
      point: {
        visible: true
      },
      load: 2,
      loop: true,
      touch: true
    };
  }

  /* It will be triggered on every slide*/
  onmoveFn(data: NguCarouselStore) {
    console.log(data);
  }
}

**Comment by nhatzbulawan** [comment]
![image](https://user-images.githubusercontent.com/3007744/47613249-0bf71000-daa5-11e8-90e8-0ba5e7dce107.png)
Thanks, 
I already had a look. Hope you can remove those samples, it confuses your visitors.

**Comment by sheikalthaf** [comment]
@nhatzbulawan Sure. Please check the upcoming version of this carousel in beta.

Please look into this stackblitz [link](https://stackblitz.com/edit/ngu-carousel-beta).

Thanks

**Comment by nhatzbulawan** [comment]
@sheikalthaf , Thank you.

**Comment by lixiaoyu0575** [comment]
> @nhatzbulawan Sure. Please check the upcoming version of this carousel in beta.
> 
> Please look into this stackblitz [link](https://stackblitz.com/edit/ngu-carousel-beta).
> 
> Thanks

But there is an Error in this version, 'ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngForOf: '. Current value: 'ngForOf: 0,1,2,3'.', which makes 'autoplay' fail. Can you fix this @sheikalthaf  
Thanks very much.
