### ISSUE TITLE
Multiple row

### ISSUE THREAD

**Issue by ArivananthamArivalagan** [sheikalthaf/ngu-carousel#127]
![tworow](https://user-images.githubusercontent.com/45373099/49044279-3f5bb600-f19b-11e8-9d30-7428782bcf36.png)
Is that possible that items can be in two rows? Will support or anyother options available?

**Comment by deepan094** [comment]
Hi Ariv,

Is this issue addressed ? I am a having a similar requirement in my project. If you have any solution for this, please share the same.

Thanks

**Comment by ArivananthamA** [comment]
Yes, I cooked the json structure to adopt the above structure.

**Comment by deepan094** [comment]
Thanks @ArivananthamArivalagan , we too did the same and searching for better solution . 👍
