### ISSUE TITLE
Carousel doesn't work with fixed width in small screen

### ISSUE THREAD

**Issue by squelix** [sheikalthaf/ngu-carousel#129]
When we resize our page, all the page freeze and bug...
We are using the fixed width.

**Comment by squelix** [comment]
We must use the `xs`, `md`... values instead of `all` to not have this problem....
I guess it's a big issue :/

**Comment by kmturley** [comment]
Looks like there is a fixed width demo here:
https://stackblitz.com/edit/angular-x2m3xa?file=app%2Fapp.component.ts

Using the values:
`grid: {xs: 0, sm: 0, md: 0, lg: 0, all: 130},`

**Comment by squelix** [comment]
Thanks
