### ISSUE TITLE
Ivy preview

### ISSUE THREAD

**Issue by kolkov** [sheikalthaf/ngu-carousel#159]
Hi! Check this issue please.
https://github.com/angular/angular/issues/30981#issuecomment-501009207

**Comment by bstaley** [comment]
This [comment](https://github.com/angular/angular/issues/30981#issuecomment-501905359) seems to indicate that `private` inputs are not allowed.

**Comment by kolkov** [comment]
@bstaley yes, we need to get fix.

**Comment by sheikalthaf** [comment]
This library is updated to latest version of angular with ivy support.

Thanks All
