### ISSUE TITLE
Unexpected token import while using ngu-carousel in universal 

### ISSUE THREAD

**Issue by ankurgarg36** [sheikalthaf/ngu-carousel#16]
Hi 
I want to use this carousel in universal project. when i run ng serve, it work perfectly. 
No problem with build, but when running application using node server it gives following error. 

![screenshot from 2018-02-19 13-08-27](https://user-images.githubusercontent.com/8677133/36366961-7a3a88a2-1576-11e8-8eef-530a1fdd64d4.png)

Please help.

**Comment by sheikalthaf** [comment]
never faced this issue. Shall i have more details on this

**Comment by StudioTOB** [comment]
Hi, 

I also have the same problem. However, I'm using firebase deploy to upload and process my universal project. I had this working on a regular universal project though. The error I'm getting is:
`Error occurred while parsing your function triggers.`

`E:\StudioTOB\functions\node_modules\@ngu\carousel\src\ngu-carousel\ngu-carousel.component.js:1
(function (exports, require, module, __filename, __dirname) { import { NguCarouselItemDirective, NguCarouselNextDirective, NguCarouselPrevDirective } from './../ngu-carousel.directive'; `

`SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.TB5X (E:\StudioTOB\functions\dist-server\main.bundle.js:1:548740)`
`

**Comment by DmitriyTretyakov** [comment]
So, can somebody recommend another carousel with support of universal and firebase?

**Comment by edakelius** [comment]
You can whitelist ngu-carousel in webpack.config.js

` 
externals: [
    nodeExternals({
      whitelist: [
        /^@ngu\/carousel/
      ]
    })
  ],
`

**Comment by sheikalthaf** [comment]
@ankurgarg36 @StudioTOB @dmitriytretyakov @edakelius Hi,

Updated the carousel to angular 6. Please check the latest and may be the error will be fixed. because now I'm using angular library. Thanks
