### ISSUE TITLE
Not compatible with Angular 9

### ISSUE THREAD

**Issue by ioannist** [sheikalthaf/ngu-carousel#173]
This library works up to Angular 8.

I was not able to make it work with Angular 9 (with Ivy enabled or disabled)

**Comment by Mallfurion** [comment]
@sheikalthaf any plans for providing support up to Angular 9?

**Comment by ioannist** [comment]
I would think no. The release section has been pretty quiet.

It's a shame cause it is a very good carousel library, but we can't stay in angular 8 forever. Does anyone know a good alternative with ongoing support? There are so many carousel packages out there, it's hard to choose.

**Comment by euangoddard** [comment]
I have made this pull request #175 to add support. The demo app is working fine with Angular 9. It just needs someone to review it really as I re-built the project from a newly generated skeleton using the latest CLI

**Comment by euangoddard** [comment]
For anyone who is interested, I've publish my fork here: https://www.npmjs.com/package/@stockopedia/carousel until the maintainer merges my PR. I've tested with Angular 9 RC8 and everything seems to be working correctly

**Comment by pkrawat1** [comment]
Thanks @euangoddard  for the update. I'm updating angularspree to angular 9, which currently has a dependency on this library. So was looking for an alternative of this library. But your changes are working fine. So thanks. 
I hope @sheikalthaf  works on the upgrade and looks at your PR soon.

**Comment by KingDarBoja** [comment]
Really appreciate the effort @euangoddard, your build does work with Angular 9 💯

**Comment by c3mohamn** [comment]
@sheikalthaf please take @euangoddard's PR asap. Thank you for your work.

**Comment by HEBOS** [comment]
@euangoddard I'm getting the following error in console: 
"ERROR TypeError: "this._nodeOutlet is undefined"

Is your fix addressing that issue?

Thanks

**Comment by sheikalthaf** [comment]
This lib is updated to Angular 9. Special thanks to @euangoddard . And also angular expert @santoshyadav198613 who is going to maintain this library.

Thanks all
