### ISSUE TITLE
How to hide prev and next button?

### ISSUE THREAD

**Issue by node1mei** [sheikalthaf/ngu-carousel#19]
Hello,
I want to hide the prev and next button, but when I don't write button tag, cause `ERROR TypeError: Cannot read property 'nativeElement' of undefined `error. Is there any option or method to hide these button? I didn't found it at documentation.

Thanks for your love and support

**Comment by sheikalthaf** [comment]
For what reason you want to hide the buttons. have you tried to hide with css

**Comment by node1mei** [comment]
Thanks for your reply.

I think mobile screen is too small to show much buttons. I wrote `style="display: none"` to button tag before open this issue, but no use. I tried to wrap button with div tag just now, and button didn't show any more.

**Comment by JackPoint** [comment]
Would be nice if there is a better option to not use the buttons. When put a (hacky) *ngIf="1==2" on the buttons, the points aren't displayed to. If it's possible, make the buttons optional and let me add an element to show the points.

**Comment by JackPoint** [comment]
Yes, but thats cheating

**Comment by 4val0v** [comment]
How to hide buttons for desktops?
Grid >= md
