### ISSUE TITLE
bug: Cannot use this on Angular 8

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [sheikalthaf/ngu-carousel#219]
Hello,

I have discovered this plugin and tried to use it but I get this error
```
client:159 ./node_modules/@ngu/carousel/fesm2015/ngu-carousel.js 937:12-24
"export 'HammerModule' was not found in '@angular/platform-browser'
```

I have added the hammer js library to the scripts array on `angular.json` and tried importing in the `main.ts` but without success

**Comment by jcollombb** [comment]
The newest version relies on Angular 9. Try installing an earlier version `npm i @ngu/carousel@1.5.5`

**Comment by tiagomsmagalhaes** [comment]
Got it to work. Thanks for the tip.

I wasn't paying attention because there is no disclaimer about this in the repo. Besides:
- The **CHANGELOG.md** link is dead
- The latest version listed on the releases tab is 1.5.3
- There is no indication of a breaking change
- The entry on npmjs apparently is unlinked to the repo.
