### ISSUE TITLE
autoprefixing styles for tiles

### ISSUE THREAD

**Issue by dottodot** [sheikalthaf/ngu-carousel#24]
Found a bit of an issue trying to get this working on older browsers. I can sort autoprefixing `ngucarousel-items` by adding the follow to my scss
```
/deep/ .ngucarousel-items {
  display: flex;
}
```
but when it comes to the tiles it a bit more complicated as the css for those is created dynamically.

Can anyone suggest a way around this or is it just a case of manually adding your own css for the breakpoints?

**Comment by sheikalthaf** [comment]
@dottodot Hi,

Carousel is updated and ngu-tile is not mandatory. Please check the latest version.

Thanks
