### ISSUE TITLE
problem with the speed (maybe with interval also)

### ISSUE THREAD

**Issue by gtzalavras** [sheikalthaf/ngu-carousel#25]
I found an issue trying to set the **speed** to **0** for the carousel.
Even if i change the value,the speed is **always the same**.
I think there is the **same problem** with **interval**.

I made it work by changing the line **293** of the file **ngu-carousel.component.js** (in src/ngu-carousel folder).

I replaced the code:
`this.userData.speed =`
with this:
`this.data.speed =`

So, at the place of **userData** i put **data** and now it works.

Can you confirm that this fixes the problem of the speed and also if there is a problem with interval value also?

**Comment by sheikalthaf** [comment]
@gtzalavras Yes there is some animation issue when the items contains heavy images, I'm planning to use webanimation to avoid it

**Comment by netlander** [comment]
Speed definitely not working.

**Comment by netlander** [comment]
Fix this bug that's making this carousel useless.

**Comment by sheikalthaf** [comment]
@netlander @gtzalavras Fixed this issue in latest build and also check the release. Thanks
