### ISSUE TITLE
Using toSlide and resetCarousel

### ISSUE THREAD

**Issue by dlewis2017** [sheikalthaf/ngu-carousel#28]
So I've been playing around with the ability to go from a 5 tile panel to (on click) a single panel carousel that pulls up the specific tile one clicked on.
I've been having trouble with this and the closest I've come to a solution is having 2 carousels and using *ngIf (true | false) depending on whether or not a tile was clicked.

**The specific part I am now stuck at, is how to open the second, single panel, carousel to the tile that was clicked in the 5 panel carousel. I'm using toSlide and resetCarousel onIt of the single panel carousel but nothing seems to be working as I expect it to and the return statements of toSlide and resetCarousel return undefined (not sure if that's what they're supposed to return)**

Any thoughts on how to achieve this?

Thanks,

-Angular version: 5
-Data Source of carousels: array of objects
-Not sure what other useful information to put

**Comment by sheikalthaf** [comment]
@dlewis2017 Soon it will be added. I'm working on an update to customize everything

**Comment by dlewis2017** [comment]
@sheikalthaf No rush at all but how soon will everything be up. Just trying to gauge if I should wait or continuing to pursue another solution I came up with.

Thanks,

**Comment by sheikalthaf** [comment]
@dlewis2017 Updated the carousel to latest version of angular. Now you can use template refernce to access the carousel feature. Thanks
