### ISSUE TITLE
Touch not working

### ISSUE THREAD

**Issue by dottodot** [sheikalthaf/ngu-carousel#30]
I have hammerjs imported in my polyfill and touch set to true but when you try and swipe through the carousel it just bounces back.

Sometimes it does works, but not always it like you have to find a special technique to get it to swipe.

I not seeing any errors either.

**Comment by Agrati** [comment]
Same problem here. Did you find a solution for this?

**Comment by dottodot** [comment]
@Agrati Unfortunately not seems intermittent too, occasionally it actually works but very hit and miss

**Comment by gbarrionuevo** [comment]
any update @dottodot @Agrati ?

**Comment by sheikalthaf** [comment]
Hi,



Sorry to say this. I have included a new condition on swipe. It the velocity of the swipe is greater than one then only it will be slide.



If u swipe slow it will be bounce back. In upcoming build i will give an option to control the velocity. Also other new features to control the carousel independently

**Comment by gbarrionuevo** [comment]
awesome, do you have an idea when it's going to be out @sheikalthaf ?

**Comment by aasmm7x** [comment]
News about velocity on swipe? The current velocity is a pain.

**Comment by AisonBird** [comment]
@sheikalthaf awesome! I disabled the velocity logic, it works fine now!

**Comment by sheikalthaf** [comment]
@AisonBird @PsychicCat @aasm-moura @gbarrionuevo @dottodot Updated the carousel to angular 6. Now velocity accepts 0 value. Thanks
