### ISSUE TITLE
Adding html over slider images only works well when clicking next button 

### ISSUE THREAD

**Issue by gbarrionuevo** [sheikalthaf/ngu-carousel#31]
I've added some html over each img, but only applies to every slide when you click next button.

First Load:

![image](https://user-images.githubusercontent.com/17553670/38498189-f97bf608-3bd9-11e8-915e-e3fe32a9e92c.png)

After clicking next 

![image](https://user-images.githubusercontent.com/17553670/38498215-0a700fb2-3bda-11e8-97cb-9fd6b9ca4d62.png)

Html:
`  <ngu-carousel [inputs]="carouselTileOne" (carouselLoad)="carouselTileOneLoad()">
                                <ngu-tile NguCarouselItem *ngFor="let tile of carouselTileOneItems; let i = index;">
                                    <div class="wBg">
                                        <div class="label-discount left-20 top-15">-30%</div>
                                        <ul class="deal-actions top-15 right-10">
                                            <li class="like-deal">
                                                <span>
                                                    <i class="fa fa-heart"></i>
                                                </span>
                                            </li>
                                        </ul>
                                        <div class="deal-store-logo store-logo">
                                            <img src="assets/images/brands/brand_01.jpg" alt="">
                                        </div>
                                        <div class="tile" [style.background]="'url(' + tile + ')'">
                                            <h1>{{i}}</h1>
                                        </div>
                                        <h4>Tile</h4>
                                        <p>content</p>
                                    </div>
                                </ngu-tile>
                                <button NguCarouselPrev class="leftRs">&lt;</button>
                                <button NguCarouselNext class="rightRs">&gt;</button>
                            </ngu-carousel>`

TS

`this.carouselTileOne = {
      grid: { xs: 2, sm: 3, md: 4, lg: 4, all: 0 },
      speed: 600,
      interval: 0,
      point: {
        visible: true,
        pointStyles: `
          .ngucarouselPoint {
            list-style-type: none;
            text-align: center;
            padding: 12px;
            margin: 0;
            white-space: nowrap;
            overflow: auto;
            box-sizing: border-box;
          }
          .ngucarouselPoint li {
            display: inline-block;
            border-radius: 50%;
            background: #6b6b6b;
            padding: 5px;
            margin: 0 3px;
            transition: .4s;
          }
          .ngucarouselPoint li.active {
              border: 2px solid rgba(0, 0, 0, 0.55);
              transform: scale(1.2);
              background: transparent;
            }
        `
      },
      load: 4,
      loop: false,
      touch: true,
      easing: 'ease',
      animation: 'lazy'
    };`

**Comment by gbarrionuevo** [comment]
@sheikalthaf  here it's, https://stackblitz.com/edit/angular-71uszj?file=app%2Fapp.component.css

This is the problem:

 .right-10 {
     right: 10px !important; 
}
  
It's fails the first time but then works when you move on

**Comment by sheikalthaf** [comment]
@gbarrionuevo 
The issue is caused because the parent element don't have position relative.

**Comment by gbarrionuevo** [comment]
@sheikalthaf  Awesome, thank you !
