### ISSUE TITLE
moveToSlide doesn't work on load

### ISSUE THREAD

**Issue by zachrickards** [sheikalthaf/ngu-carousel#35]
I'd like to move to a particular slide when the carousel loads or "move to end" of carousel when the carousel loads

**Comment by sheikalthaf** [comment]
Hi @zachrickards ,

I have depreciated the service instead of that you can use template reference. I will push the update tomorrow and you will able to use that feature

Thanks

**Comment by sheikalthaf** [comment]
Hi @zachrickards 

This issue is fixed. read this [release](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.9-beta-2)

**Comment by sheikalthaf** [comment]
@zachrickards Updated the carousel. Please check. Thanks
