### ISSUE TITLE
NGX or NGU?

### ISSUE THREAD

**Issue by farhankhwaja** [sheikalthaf/ngu-carousel#36]
Hi, I wanted to understand why did you depreciate the NGX project and started the NGU project. If you can help with this.

Thanks

**Comment by lakshmajim** [comment]
@sheikalthaf ,
Will it be used for non universal angular projects ??

**Comment by sheikalthaf** [comment]
Yes ofcourse

**Comment by sheikalthaf** [comment]
@lakshmajim There is no side effects

**Comment by lakshmajim** [comment]
@sheikalthaf , thank you.
