### ISSUE TITLE
Using moveToSlide in lifeCycle functions breaks the previous button

### ISSUE THREAD

**Issue by zachrickards** [sheikalthaf/ngu-carousel#37]
Using AfterViewChecked and AfterContentChecked to wrap moveToSlide causes the button click for previous to no long function.

```
ngAfterContentChecked() {
    this.moveToSlide();
  }

  initDataFn(key: NguCarouselStore) {
    this.carouselToken = key.token;
    this.slideItems = key.items;
  }

  moveToSlide() {
    if (this._benefits.length > 0 && !isNaN(this.slideItems)) {
      const slide = Math.round(this._benefits.length / this.slideItems);

      this.carousel.moveToSlide(this.carouselToken, slide, false);
    }
  }```

**Comment by sheikalthaf** [comment]
Hi,



How can i reproduce the issue?

If possible create a stackblitz.



Thanks for reporting

**Comment by sheikalthaf** [comment]
Hi @zachrickards 

This issue is addressed. read this [release](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.9-beta-2)
