### ISSUE TITLE
Is it possible to stop the sliding of the items?

### ISSUE THREAD

**Issue by silversonicaxel** [sheikalthaf/ngu-carousel#39]
I could not find a way to have the slider stopped to the first item. I need to slide to the second item only if I click a button "next" but I could not find a way to do it. Thanks.

**Comment by sheikalthaf** [comment]
Hi @silversonicaxel ,

You can able to stop the auto slider by removing interval from inputs. If you want to stop touch then remove touch too

Thanks

**Comment by silversonicaxel** [comment]
Ah, ok, I would make it more visible in the documentation. Thanks!
