### ISSUE TITLE
Angular 6 & rxjs compatability

### ISSUE THREAD

**Issue by ImranAhmed** [sheikalthaf/ngu-carousel#43]
Hi,

I've just tried this with the new Angular v6.0. I am getting the following error:

ERROR in node_modules/@ngu/carousel/src/ngu-carousel.service.d.ts(1,10): error TS2305: Module '"../node_modules/rxjs/Subject"' has no exported member 'Subject'.

As a temp fix you can install the following package for backward compatibility but it would be good to remove this dependency.

`npm install rxjs-compat@6 --save`

**Comment by DukeCaesar** [comment]
As a temporary solution, you may try to install the 1.4.1 version of ngu-carousel, which may work as well.
The command is as below:
npm install @ngu/carousel@^1.4.1 --save

**Comment by beyondtheobservableuniverse** [comment]
Same error in the 1.4.1 version.

**Comment by EddieBenji** [comment]
It would be really helpful to get this project updated to latest Rxjs, please!

**Comment by pantonis** [comment]
Any news on the update?

**Comment by sheikalthaf** [comment]
@ImranAhmed @pantonis @beyondtheobservableuniverse Update the carousel to angular 6. Please check release. Thanks

**Comment by pantonis** [comment]
Thanks will test and let you know if any issue arise
