### ISSUE TITLE
Delay animation

### ISSUE THREAD

**Issue by sarnecki-cic** [sheikalthaf/ngu-carousel#45]
Hi I'm curious if it's possible to delay first slide animation. I've got two sliders next to each other and I want the same animation speed and interval, but I need one of them to start a bit later.

Thanks for your help.

**Comment by sheikalthaf** [comment]
Hi @sarnecki-cic ,

Thanks for the suggestion I also faced the same problem. I will implement this feature and push the update

**Comment by sheikalthaf** [comment]
@sarnecki-cic , 

This feature is now implemented. read this [release](https://github.com/sheikalthaf/ngu-carousel/releases/tag/v1.4.9-beta-2)

**Comment by sheikalthaf** [comment]
@sarnecki-cic This changes is now in latest version. Thanks
