### ISSUE TITLE
Allow custom HTML for points

### ISSUE THREAD

**Issue by drazafsky** [sheikalthaf/ngu-carousel#46]
It would be very helpful to be able to define our own html for the points instead of just the css. For instance, I'd like to be able to show a thumbnail of all the images in the carousel. It seems that the html for the points is hardcoded to be empty li tags though and I haven't found a way to override this.

**Comment by sheikalthaf** [comment]
Hi,

I already done this features and need to push the update. i will push the update tomorrow

Thanks

**Comment by sheikalthaf** [comment]
Hi @drazafsky ,

I have added new beta version to try and need your feedback on this

Please install the beta version by `npm i @ngu/carousel@1.4.9-beta-2 -S`

**Comment by drazafsky** [comment]
@sheikalthaf Thank you! I'll test it out later this week and provide feedback.
