### ISSUE TITLE
Rxjs 6 error

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [sheikalthaf/ngu-carousel#47]
ERROR in node_modules/@ngu/carousel/src/ngu-carousel.service.d.ts(1,10): error TS2305: Module '".../ui/node_modules/rxjs/Subject"' has no exported member 'Sub
ject'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

Please update the Rxjs and Angular to version 6.

**Comment by gfoo** [comment]
duplicate #43

**Comment by spartanPAGE** [comment]
Install rxjs-compat

**Comment by EddieBenji** [comment]
Please, update the Rxjs and Angular to version 6.
In the meantime, I have installed the rxjs-compat library. However, this will disappear when the version 7 of Rxjs comes out.

**Comment by i5coding** [comment]
Yes, hope can support new version of rxjs, thanks  a lot~

**Comment by sheikalthaf** [comment]
@gfoo @beyondtheobservableuniverse @spartanPAGE @i5coding @EddieBenji Hi,

I also want to upgrade but it will only support angular 6 projects only. Then i have to drop support for angular 5 projects

**Comment by DukeCaesar** [comment]
As suggested by spartanPAGE, we could install rxjs-compat as a temporary solution:

npm install rxjs-compat --save

**Comment by EddieBenji** [comment]
Hi @sheikalthaf, do you think in the near future you could update to angular 6?
Why don't you create a new repo where you can maintain the code for angular 6 projects?


Thank you.

**Comment by artaommahe** [comment]
@sheikalthaf just make it in separate branch and publish new major version to npm. It's annoying that we forced to use `rxjs-compat` for a single lib with one rxjs import. `rxjs-compat` using increases bundle size

**Comment by ImranAhmed** [comment]
I don't think it's a good idea to have the project dependency on rxjs-compat library lying around. As most of us are learning the new rxjs v6 library it's too easy to to slip back into the old way of doing things without it raising a compile time error. A bump to v6 would be highly appreciated.

**Comment by artaommahe** [comment]
Looks like last version (` v1.4.9-beta-2`) does not use rxjs at all so we can remove `rxjs-compat` usage with it (already tried and it works)

**Comment by sheikalthaf** [comment]
@artaommahe @ImranAhmed @EddieBenji @DukeCaesar @i5coding @beyondtheobservableuniverse @spartanPAGE Updated the carousel to latest version of the angular. Please check release. Thanks

**Comment by EddieBenji** [comment]
Thank you @sheikalthaf !

Will check!
