### ISSUE TITLE
Points don't render after component init

### ISSUE THREAD

**Issue by manofearth** [sheikalthaf/ngu-carousel#51]
version: 1.4.9-beta-2

**Actual behavior**
Try this reproduction: https://angular-ngu-carousel-bug.stackblitz.io/
1. Press "Show" button
2. Notice absence of carousel points
3. Pres "Detect Changes"
4. Notice carousel points have rendered
5. Press "Next"
6. Notice active carousel point hasn't changed
7. Pres "Detect Changes"
8. Notice active carousel point has changed

**Expected behavior**
1. Press "Show" button
2. Carousel points should be rendered
3. Press "Next"
4. Active point should be changed

P.S. In NPM version of library component field `activePoint` named as `activeSlide`

**Comment by sheikalthaf** [comment]
@manofearth 

Thanks for reporting. Now I'm marked for checks when slide changes.

**Comment by sheikalthaf** [comment]
@manofearth This issue is fixed in latest build . Please check release. Thanks
