### ISSUE TITLE
onresize how to reset the grid

### ISSUE THREAD

**Issue by prashantkapate** [sheikalthaf/ngu-carousel#52]
My requirement is when I resize my window, I am changing the no of icons, same should be reflect to carousel grid as well.

How to achieve this.

ex: when I load the page I have 8 icons and carousel also showing the 8 icons. After resizing icons changed to 7 but carousel grid icons are not changing.

**Comment by sheikalthaf** [comment]
@prashantkapate Please check the [demo](https://stackblitz.com/edit/ngu-carousel-demo) to reset the carousel. Thanks
