### ISSUE TITLE
Demo no working

### ISSUE THREAD

**Issue by CarMoreno** [sheikalthaf/ngu-carousel#59]
Hi, I am trying test your angular carrousel component  but right now not working, the output error is:

`Unhandled promise rejection 
TypeError: r.scriptLanguage is undefined
Stack trace:
generateConfig@https://c.staticblitz.com/assets/engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3:13655
start@https://c.staticblitz.com/assets/engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3:22715
me@https://c.staticblitz.com/assets/preview-fe7237b13d780dbf847da.js:1:23893
[1262]/window._preboot/<@https://c.staticblitz.com/assets/preview-fe7237b13d780dbf847da.js:1:24408
u@https://c.staticblitz.com/assets/common-dd6c1ca1865a48151a33a.js:1:23777
T/<@https://c.staticblitz.com/assets/common-dd6c1ca1865a48151a33a.js:1:23899
f@https://c.staticblitz.com/assets/common-dd6c1ca1865a48151a33a.js:1:26604
`

Test in Mozilla 60.0.2

**Comment by sheikalthaf** [comment]
@CarMoreno Hi,

try this https://stackblitz.com/github/sheikalthaf/ngu-carousel

**Comment by CarMoreno** [comment]
@sheikalthaf thanks, this new link working.
