### ISSUE TITLE
carouselLoad callback not called if slides added

### ISSUE THREAD

**Issue by esoyke** [sheikalthaf/ngu-carousel#61]
I am using the carouselLoad callback function to track what slide we are currently on, as the event passed is the slide index. I do this so I can hide the left nav button on the 1st slide and the right nav on the last slide so you can't jump from last back to first going to the right or first to last going to the left.

This works great until I add slides dynamically to the carousel. After doing so, this event isn't called on the original slides. For instance if I begin with 3 slides, jumping from slide index 0>1 and 1>2 (and reverse) calls the event. If I dynamically add another slide to the data, I can navigate to it fine but the event is now only called when going from index 2>3 or 3>2. It is no longer called on navigations between the first 3 slides.

**Comment by sheikalthaf** [comment]
@esoyke Hi,

Now you can control the carousel by template reference. Please check the [demo](https://stackblitz.com/edit/ngu-carousel-demo) in stackblitz Thanks
