### ISSUE TITLE
sliding by using finger on mobile is not working properly

### ISSUE THREAD

**Issue by prajaktatkare1234** [sheikalthaf/ngu-carousel#64]
Below is the config
  public carouselOne: NguCarousel;
 this.carouselOne = {
      grid: {xs: 1, sm: 1, md: 1, lg: 1, all: 0},
      slide: 1,
      point: {
        visible: false
      },
      touch: true,
      loop: true,
      easing: 'ease',
    }

**Comment by shansubra** [comment]
Try this:

In app.module.ts add these lines:

```
import * as Hammer from 'hammerjs';
  import { HammerGestureConfig, HAMMER_GESTURE_CONFIG } from '@angular/platform-browser';

  export class HammerConfig extends HammerGestureConfig {
    overrides = <any>{
      'swipe': { direction: Hammer.DIRECTION_ALL }
    };
  }

@NgModule({
    declarations: [
      AppComponent
    ],
    imports: [
      BrowserModule
    ],
    providers: [
      {
        provide: HAMMER_GESTURE_CONFIG,
        useClass: HammerConfig
      }
    ],
    bootstrap: [AppComponent]
  })
  export class AppModule { }
```

**Comment by Gordondalos** [comment]
ERROR in Error during template compile of 'HammerCo
nfig'
  Class HammerConfig in D:/project/b2go/c2go-fronte
nd/src/app/app.module.ts extends from a Injectable
in another compilation unit without duplicating the
 decorator
    Please add a Injectable or Pipe or Directive or
 Component or NgModule decorator to the class.

**Comment by shansubra** [comment]
Can you please post your code here?

**Comment by stephenmacnaughtan** [comment]
I get the same error when trying to add this code. Also carousels are not working on IOS, both on the demo site, and on our build.

**Comment by mhosman** [comment]
Same issue here!!! Swipe is working but is not working properly. Sometimes goes ok, sometimes goes back to the previous item. Buggy swipe.

**Comment by shansubra** [comment]
Guys, please refer to this thread for my comments. I hope it should work now :)

https://github.com/sheikalthaf/ngu-carousel/issues/65

**Comment by sheikalthaf** [comment]
@mhosman @stephenmacnaughtan @shansubra Please check the latest build. Thanks
