### ISSUE TITLE
how to build the module?

### ISSUE THREAD

**Issue by hohler** [sheikalthaf/ngu-carousel#67]
How can I build the module so I get the same output as the npmjs package?

I tried `npm run packagr` but this creates a completely different dist.tgz file that's not working after installing in an Angular App.

Please help.

**Comment by sheikalthaf** [comment]
@hohler Please clone the updated repo. 
Step 1: npm install
Step 2: ng build --prod --project carousel
Step 3: ng serve

Thanks
