### ISSUE TITLE
Carousel reset and moveToSlide are not working

### ISSUE THREAD

**Issue by gaestradaaedo** [sheikalthaf/ngu-carousel#68]
I'm implementing a dynamic inputs carousel and everytime the content of the inputs is changed I'm using:
- this._carouselService.reset(this.carouselToken);
- this._carouselService.moveToSlide(this.carouselToken, 0, false);

But nothing happens in the carousel. I even copied the "Tile with Service" example you give in the Readme as it is with the Reset button but even with a normal implementation still doesn't work.

Can you help me please?

Thanks for the support.

**Comment by gaestradaaedo** [comment]
Also there is no way to prove it works. The demo supposed to be in the page https://sheikalthaf.github.io/ngu-carousel throws you a 404.

**Comment by sheikalthaf** [comment]
@gaestradaaedo Now you can use template reference to control carousel in latest version. Thanks
