### ISSUE TITLE
Cannot find service to reset

### ISSUE THREAD

**Issue by bdairy** [sheikalthaf/ngu-carousel#71]
The whole package is missed up,, it is not related to the example

**Comment by sheikalthaf** [comment]
@bdairy Hi,

I have removed the service in latest build for some flexibility.

Published a build with angular 6 upgrade in beta.
Check this stackblitz [link](https://stackblitz.com/edit/ngu-carousel-ng6) to know the breaking changes.

Once testing complete then i will move it to master

**Comment by sheikalthaf** [comment]
@bdairy Now you can use template reference to control carousel in latest version. Thanks

**Comment by bdairy** [comment]
Still don't know how to reset??
