### ISSUE TITLE
point true not work at 1.4.9-beta-2

### ISSUE THREAD

**Issue by VictorLULI** [sheikalthaf/ngu-carousel#72]
"Point is removed from the carousel instead of that you can create your own point styles by accessing the carousel. This step is taken based on the feedback of the developers“

A newbie, Not quite clear how to accessing the carousel to create point? I checked the source code, looks like  point: { visible: true } is still there...but didn't work
please show me more tips, thanks.

**Comment by VictorLULI** [comment]
@sheikalthaf 
great..thanks for help

**Comment by sheikalthaf** [comment]
@VictorLULI I hope you got the answer.
