### ISSUE TITLE
pointer don't update when using ChangeDetectionStrategy.OnPush and (onMove) is not set

### ISSUE THREAD

**Issue by ftabashir** [sheikalthaf/ngu-carousel#76]
when you use ngu-carousel in a component which its change detection strategy is `OnPush`, if you don't set the `(onMove)` output then pointer don't reflect the slide position. see [this stackblitz](https://stackblitz.com/edit/ngu-carousel-issue?embed=1&file=src/app/app.component.html).

the workaround is to set `(onMove)="{}"` for `<ngu-carousel>`
but why this issue happen?

**Comment by sheikalthaf** [comment]
@ftabashir Please check #83 for the answer. Thanks
