### ISSUE TITLE
loop not working properly in version 1.5.1.  

### ISSUE THREAD

**Issue by yuveliremil** [sheikalthaf/ngu-carousel#85]
After upgrade from 1.4.8 to 1.5.1  loop not working properly. When click next button it return to 1 slide, but when click prev button carousel doesn't return last slide. Same issue in RTL too.
Any ideas about how to fix it ?????

with version 1.4.8  all work fine.  But it required rxjs-compat.  Example:
http://www.annular.themeseason.com/landing

**Comment by sheikalthaf** [comment]
@yuveliremil Hi,

Thanks for reporting. Will fix this

**Comment by sheikalthaf** [comment]
@samuray500 Already fixed this. Need to push an update

**Comment by sheikalthaf** [comment]
@yuveliremil @samuray500 Fixed this issue in latest build. Please check release
