### ISSUE TITLE
Autoplay doesn't work

### ISSUE THREAD

**Issue by sarnecki-cic** [sheikalthaf/ngu-carousel#89]
Hi,
Although I define interval timing, my carousel doesn't want to autoplay. I've even tried to add interval to your demo on stackblitz and it doesn't move as well. Is there anything else I should add to make my carousel move automatically?
Thanks in advance.

**Comment by sheikalthaf** [comment]
@sarnecki-cic please add loop: true. Interval need loop to true.

Thanks
