### ISSUE TITLE
Previous btn not going back to the last slide when loop mode is activated

### ISSUE THREAD

**Issue by samuray500** [sheikalthaf/ngu-carousel#91]
I have this config:
public carouselConfig: NguCarouselConfig = {
    grid: { xs: 1, sm: 1, md: 1, lg: 1, all: 0 },
    slide: 1,
    speed: 950,
    interval: {
      timing: 5000,
      initialDelay: 2000
    },
    point: {
      visible: true
    },
    load: 2,
    loop: true,
    touch: true,
    easing: 'cubic-bezier(0, 0, 0.2, 1)'
  };

The carousel is changing slides normally and when it reach the end it animates back to the first slide like it's supposed to.
The expected behavior if i click on the previous btn at this point is going back to the last slide of the list, but nothing is happening, only next btn is working.

**Comment by sheikalthaf** [comment]
@samuray500 Fixed this issue in latest build. Thanks
