### ISSUE TITLE
Can someone please review the readme and imporve it

### ISSUE THREAD

**Issue by DoryZi** [sheikalthaf/ngu-carousel#92]
The readme with the examples and the docs isn't very clear. It's not clear how to use this, the first example has two carousel and overall it's very confusing, it requires someone to re-visit and explain it a little better.

**Comment by sheikalthaf** [comment]
@DoryZi Hi,

Please follow this [link](https://stackblitz.com/edit/ngu-carousel-demo) for demo

**Comment by rbroen** [comment]
@sheikalthaf : thank you, the other demos did not work for me

**Comment by sheikalthaf** [comment]
@DoryZi document is updated. Thanks
