### ISSUE TITLE
cannot set grid breakpoints

### ISSUE THREAD

**Issue by harellevy** [sheikalthaf/ngu-carousel#94]
I have to deal with greater screen sizes than the default breakpoints. I'll be happy if i had the option to configure the grid breakpoints as: 
i.e for default behavior
carouselService.configuration.gridBreakpoints = {
    xs: 768;
    sm: 1024;
    md: 1400;
    lg: 1920;
};

or as a directive to override for specific carousel in page etc.

**Comment by sheikalthaf** [comment]
@harellevy Hi,

This feature request is on roadmap. Once implemented let you know.

Thanks

**Comment by harellevy** [comment]
Cool, thanks.

**Comment by ramesh-1986** [comment]
I am also waiting to see this done

**Comment by zuo305** [comment]
Waiting too.

**Comment by SerhiiTsybulskyi** [comment]
+1

**Comment by rat-matheson** [comment]
+1
