### ISSUE TITLE
nguCarouselDef trackBy

### ISSUE THREAD

**Issue by sarnecki-cic** [sheikalthaf/ngu-carousel#98]
Do you plan to implement trackBy in nguCarouselDef, working similar as in ngFor?
That would be extremely useful when carousel data is updated dynamically.

**Comment by sheikalthaf** [comment]
@sarnecki-cic Hi,

Implemented this feature and will push the update.

Thanks

**Comment by sheikalthaf** [comment]
@sarnecki-cic This feature is implemented. Please check release.

Thanks

**Comment by lawler** [comment]
I see your change, but when using [trackBy] in conjuction with [dataSources] I am only getting undefined values for index and item in my method.  When I change the line from:  

`return this.trackBy ? this.trackBy(item.dataIndex, item.data) : item;`
to
`return this.trackBy ? this.trackBy(_i, item) : item;`

I do see the index and the item data. Am I missing something? I couldn't figure out where dataIndex and data was being set on the item.
