### ISSUE TITLE
Sliding problem on Touch Devices

### ISSUE THREAD

**Issue by Omi0** [sheikalthaf/ngu-carousel#99]
I am having a problem with touch devices. Sometimes it slides, sometimes it doesn't. Sometime it just not responding. But when I use a pagination or buttons afterwards everything works flawlessly. Changing velocity settings looks like has no effect.

Having this issue on both Andoroid and iOS devices.

**Comment by sheikalthaf** [comment]
@Omi0 Please check the latest version. And please let me know. Thanks

**Comment by Omi0** [comment]
@sheikalthaf you've nailed it. Problem is gone

**Comment by sheikalthaf** [comment]
@Omi0 Thanks for the confirmation.

**Comment by corentin-gautier** [comment]
@sheikalthaf would it be possible to have this fix on 1.4.8 ? I can't update to the latest version since it's not stable yet. Or do you know how I can fix this when using version 1.4.8 ?

**Comment by Omi0** [comment]
@sheikalthaf actually this issue is still present expecially on a devices with a big devicePixelRatio. For example on one device with pixel ratio 2.0 - it works good. But on another with pixelRatio 3.0. It just doesn't work... I can submit a video to show you an example
